#SPDX-License-Identifier: MIT-0
---
# tasks file for phpmyadmin
- name: Kill existing service
  ansible.builtin.shell: |
    docker service ls | grep phpmyadmin && docker service rm phpmyadmin || true
  when: "'manager' in group_names"

- name: Create phpMyAdmin Docker service
  docker_swarm_service:
    name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    publish:
      - target_port: 80
        published_port: 8082
    env:
      PMA_HOST: db
      PMA_PORT: "3306"
      PMA_USER: "Admin-usr"
      PMA_PASSWORD: "Passw0rd"
    labels:
      traefik.enable: "true"
      traefik.http.routers.phpmyadmin.rule: "Host(`phpmyadmin.test`)"
      traefik.http.routers.phpmyadmin.entrypoints: "web"
      traefik.http.services.phpmyadmin.loadbalancer.server.port: "80"
    networks:
      - traefik-net
    restart_config:
      condition: any
    update_config:
      parallelism: 1
      delay: 10s
    placement:
      constraints:
        - node.hostname == bdd-srv
  when: "'manager' in group_names"
