#SPDX-License-Identifier: MIT-0
---
# tasks file for swarm

- name: Check if the node is already part of a swarm
  command: docker info -f '{{ "{{ .Swarm.LocalNodeState }}" }}'
  register: swarm_state
  changed_when: false
  failed_when: false

- name: Check if this node is the swarm manager
  command: docker info -f '{{ "{{ .Swarm.ControlAvailable }}" }}'
  register: is_manager
  changed_when: false
  failed_when: false
  when: swarm_state.stdout == 'active'

- name: Check current swarm manager IP
  command: docker node ls --format "{{ "{{ .ManagerStatus }}" }}" --filter "role=manager"
  register: current_manager
  changed_when: false
  failed_when: false
  when:
    - swarm_state.stdout == 'active'
    - is_manager.stdout == 'true'

- name: Leave swarm only if configuration needs to change
  command: docker swarm leave --force
  when:
    - swarm_state.stdout == 'active'
  register: swarm_leave
  ignore_errors: true

- name: Initialize the swarm on manager if not already correct
  command: docker swarm init --advertise-addr {{ ansible_host }}
  when:
    - inventory_hostname in groups['manager']
    - (swarm_state.stdout != 'active' or swarm_leave.changed)
  register: swarm_init
  changed_when: "'Swarm initialized' in swarm_init.stdout"

- name: Get worker join token from the manager
  command: docker swarm join-token -q worker
  when: inventory_hostname in groups['manager']
  register: swarm_worker_token
  changed_when: false
  retries: 3
  delay: 2

- name: Set worker join token fact
  set_fact:
    worker_join_token: "{{ hostvars[groups['manager'][0]].swarm_worker_token.stdout }}"
  when: inventory_hostname in groups['workers']

- name: Join the worker node to the swarm if needed
  command: >
    docker swarm join
    --token {{ worker_join_token }}
    {{ hostvars[groups['manager'][0]].ansible_host }}:2377
  when:
    - inventory_hostname in groups['workers']
    - (swarm_state.stdout != 'active' or swarm_leave.changed)
  register: join_result
  changed_when: "'This node joined a swarm as a worker' in join_result.stdout"

