- name: Kill existing service
  ansible.builtin.shell: |
    docker service ls | grep nginx && docker service rm nginx || true
  when: "'manager' in group_names"

- name: Tag web hosts
  ansible.builtin.shell: |
    docker node update --label-add role=web web1-srv
    docker node update --label-add role=web web2-srv
  when: "'manager' in group_names"
- name: Create NGINX Docker service
  community.docker.docker_swarm_service:
    name: nginx
    image: nginxdemos/hello
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx.rule: "Host(`nginx.test`)"
      traefik.http.routers.nginx.entrypoints: "web"
      traefik.http.services.nginx.loadbalancer.server.port: "80"
    networks:
      - traefik-net
    mode: replicated
    replicas: 2
    restart_config:
      condition: any
    update_config:
      parallelism: 1
      delay: 5s
    placement:
      constraints:
        - node.labels.role == web
  when: "'manager' in group_names"
