- name: Tag web hosts
  ansible.builtin.shell: |
    docker node update --label-add role=web web1-srv
    docker node update --label-add role=web web2-srv
  when: "'manager' in group_names"

- name: Create NGINX Docker service
  community.docker.docker_swarm_service:
    name: nginx
    image: nginxdemos/hello
    publish:
      - target_port: 80
        published_port: 88
    mode: replicated
    replicas: 2
    restart_config:
      condition: any
    update_config:
      parallelism: 1
      delay: 5s
    placement:
      constraints:
        - node.labels.role == web
  when: "'manager' in group_names"
