#SPDX-License-Identifier: MIT-0
---
# tasks file for traefik
- name: Installer pip3
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Installer le module docker pour Python (via apt)
  ansible.builtin.package:
    name: python3-docker
    state: present

- name: Kill existing service
  ansible.builtin.shell: |
    docker service ls | grep traefik && docker service rm traefik || true
  when: "'manager' in group_names"

- name: Créer le réseau overlay traefik-net
  community.docker.docker_network:
    name: traefik-net
    driver: overlay
    attachable: yes
  when: "'manager' in group_names"

- name: Déployer Traefik sur un worker spécifique avec Swarm
  community.docker.docker_swarm_service:
    name: traefik
    image: traefik:v2.10
    args:
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=traefik-net"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.insecure=true"
      - "--metrics.prometheus=true"
    publish:
      - target_port: 80
        published_port: 80
        protocol: tcp
        mode: host
      - target_port: 443
        published_port: 443
        protocol: tcp
        mode: host
      - target_port: 8080
        published_port: 8080
        protocol: tcp
        mode: host
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
    networks:
      - traefik-net
    placement:
      constraints:
        - node.hostname == proxy-srv
    restart_config:
      condition: any
    state: present
  when: "'manager' in group_names"
