#SPDX-License-Identifier: MIT-0
---
# tasks file for grafana
- name: Kill existing service
  ansible.builtin.shell: |
    docker service ls | grep grafana && docker service rm grafana || true
  when: "'manager' in group_names"

- name: Installer le module docker pour Python (via apt)
  ansible.builtin.package:
    name: python3-docker
    state: present

- name: Supprimer le dossier /grafana
  ansible.builtin.file:
    path: /grafana
    state: absent
  when: ansible_hostname == 'monit-srv'

- name: Créer le dossier /grafana sur le noeud de monitoring
  ansible.builtin.file:
    path: /grafana
    state: directory
    owner: 472
    group: 472
    mode: '0775'
  when: ansible_hostname == 'monit-srv'

- name: Créer le dossier de provisioning des datasources Grafana
  ansible.builtin.file:
    path: /etc/grafana/provisioning/datasources
    state: directory
    owner: 472
    group: 472
    mode: '0755'
  when: ansible_hostname == 'monit-srv'

- name: Provisionner la datasource Prometheus dans Grafana
  ansible.builtin.copy:
    src: prometheus-datasource.yml
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    owner: 472
    group: 472
    mode: '0644'
  when: ansible_hostname == 'monit-srv'

- name: Déployer Grafana sur un worker spécifique avec Swarm
  community.docker.docker_swarm_service:
    name: grafana
    image: grafana/grafana:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: "Host(`grafana.test`)"
      traefik.http.routers.grafana.entrypoints: "web"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
    networks:
      - traefik-net
    mounts:
      - source: /grafana
        target: /var/lib/grafana
        type: bind
      - source: /etc/grafana/provisioning/datasources
        target: /etc/grafana/provisioning/datasources
        type: bind
    placement:
      constraints:
        - node.hostname == monit-srv
    restart_config:
      condition: any
    state: present
    env:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "Passw0rd"
  when: "'manager' in group_names"
