[docker]
  web1-srv ansible_host=192.168.10.11 ansible_user=web1-usr
  web2-srv ansible_host=192.168.10.13 ansible_user=web2-usr
  proxy-srv ansible_host=192.168.10.12 ansible_user=proxy-usr
  bdd-srv ansible_host=192.168.10.10 ansible_user=bdd-usr
